### ISSUE TITLE
Invalid data structure: data.id.id is not a string

### ISSUE THREAD

**Issue by PointerSoftware** [askrella/whatsapp-chatgpt#233]
I am getting this error after I send whatsapp message to the AI `Invalid data structure: data.id.id is not a string` I setup everything correctly accourding to the documentation.
[Screenshot](https://i.postimg.cc/Px5bKWTQ/error.png)

**Comment by envieme** [comment]
It started happening since y'day. The app was running well for all these days for me. And now I changed /node_modules/whatsapp-web.js/src/structures/Message.js line 91 to this.deviceType = 'android'; just to check but no messages seem to go out... 

I am wondering how come suddenly without any changes to code this can happen today? Was node js updated?

**Comment by envieme** [comment]
whatsapp web node module has changed and it has introduced errors. Those who installed Whatsapp-Chatgpt recently pulling new node modules or those who happen to update from now may see the error until it is fixed in npm for the library. 

For now, quick fix is:

in [/node_modules/whatsapp-web.js/src/structures/Message.js] line 91:

`change: this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web';
`
to

`this.deviceType = typeof data.id.id === 'string' && data.id.id.length > 21 ? 'android' : typeof data.id.id === 'string' && data.id.id.substring(0, 2) === '3A' ? 'ios' : 'web';`

and 

/node_modules/whatsapp-web.js/src/util/Injected.js around line 250:

Change code to this:

        ```
const newId = await window.Store.MsgKey.newId(); //change

        const newMsgId = new window.Store.MsgKey({
            from: meUser,
            to: chat.id,
            id: window.Store.MsgKey.newId(),
            id: newId, // change
            participant: isMD && chat.id.isGroup() ? meUser : undefined,
            selfDir: 'out',
        });
        
It should fix the errors and message not sending issue.


```
