### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by yaggit** [askrella/whatsapp-chatgpt#32]
Exception:

file:///E:/whatsapp-chatgpt-master/whatsapp-chatgpt-master/node_modules/chatgpt/build/index.js:132
      throw new Error("Invalid environment; fetch is not defined");
            ^

Error: Invalid environment; fetch is not defined
    at new ChatGPTAPI (file:///E:/whatsapp-chatgpt-master/whatsapp-chatgpt-master/node_modules/chatgpt/src/chatgpt-api.ts:152:13)
            ^
Error: Invalid environment; fetch is not defined
    at new ChatGPTAPI (file:///E:/whatsapp-chatgpt-master/whatsapp-chatgpt-master/node_modules/chatgpt/src/chatgpt-api.ts:152:13)    at E:\whatsapp-chatgpt-master\whatsapp-chatgpt-master\src\index.ts:10:13

**Comment by parentyazilim** [comment]
The error message "Invalid environment; fetch is not defined" usually indicates that the fetch function, which is commonly used for making HTTP requests, is not available in the environment where the code is being run. This error can occur when running JavaScript code outside of a browser environment, such as in a Node.js runtime.

To resolve this error, you may need to install a package that provides the fetch function in your Node.js environment. One popular package for this is node-fetch. You can install it using npm by running the following command:

```sql
npm install node-fetch
```

Once you have installed node-fetch, you can modify the code to use it instead of the built-in fetch function. You can do this by adding the following line to the top of the file:

```javascript
const fetch = require('node-fetch');
```
This line will import the fetch function from the node-fetch package and make it available for use in your code.
